/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Node.js 侧的编译选项对象。 */
export interface JsCompileOptions {
  /** 是否压缩输出 CSS。 */
  minify?: boolean
  /** 源文件路径，用于解析 @import。 */
  filename?: string
}
/** 暴露给 Node.js 的异步编译函数。 */
export declare function compileLess(source: string, options?: JsCompileOptions | undefined | null): string
